const UPDATE_AUTHENTICATION = "UPDATE_AUTHENTICATION"
const UPDATE_USER_LOADING = "UPDATE_USER_LOADING"
const UPDATE_SUBNAV = "UPDATE_SUBNAV"
const UPDATE_NAVBAR = "UPDATE_NAVBAR"
const UPDATE_TITLE = "UPDATE_TITLE"

const Update = {
    authentication: UPDATE_AUTHENTICATION,
    userLoading: UPDATE_USER_LOADING,
    subNav: UPDATE_SUBNAV,
    navBar: UPDATE_NAVBAR,
    title: UPDATE_TITLE
}

export default Update